# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/X/Digital-Recognition/Digital-Recognition.srcs/sources_1/ip/axi_iic_0/axi_iic_0.xci
# IP: The module: 'axi_iic_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/X/Digital-Recognition/Digital-Recognition.srcs/sources_1/ip/axi_iic_0/axi_iic_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_iic_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: g:/X/Digital-Recognition/Digital-Recognition.srcs/sources_1/ip/axi_iic_0/axi_iic_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_iic_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: g:/X/Digital-Recognition/Digital-Recognition.srcs/sources_1/ip/axi_iic_0/axi_iic_0.xci
# IP: The module: 'axi_iic_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/X/Digital-Recognition/Digital-Recognition.srcs/sources_1/ip/axi_iic_0/axi_iic_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_iic_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: g:/X/Digital-Recognition/Digital-Recognition.srcs/sources_1/ip/axi_iic_0/axi_iic_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_iic_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
